import 'package:forge_core/forge_core.dart';
import 'package:forge_backend/forge_backend.dart';
import 'features/auth/login_screen.dart';
import 'features/auth/signup_screen.dart';
import 'features/home/home_screen.dart';
import 'features/profile/profile_screen.dart';
import 'features/subscription/subscription_screen.dart';
import 'features/admin/admin_screen.dart';

/// App routes — add your GoRoute definitions here.
/// This file is generated by `forge generate` but safe to edit.
final List<RouteBase> appRoutes = [
  GoRoute(
    path: '/',
    name: 'home',
    builder: (context, state) => const HomeScreen(),
  ),
  GoRoute(
    path: '/admin',
    name: 'admin',
    builder: (context, state) => const AdminScreen(),
    redirect: (context, state) {
      final backend = sl<BackendService>();
      return ForgeRoleGuard.redirect(
        currentRole: backend.currentUser?.role,
        allowedRoles: const [ForgeRole.admin],
        redirectLocation: '/',
      );
    },
  ),
  GoRoute(
    path: '/login',
    name: 'login',
    builder: (context, state) => const LoginScreen(),
  ),
  GoRoute(
    path: '/signup',
    name: 'signup',
    builder: (context, state) => const SignupScreen(),
  ),
  GoRoute(
    path: '/profile',
    name: 'profile',
    builder: (context, state) => const ProfileScreen(),
  ),
  GoRoute(
    path: '/subscription',
    name: 'subscription',
    builder: (context, state) => const SubscriptionScreen(),
  ),
];
