import 'package:forge_core/forge_core.dart';
import 'package:forge_core/src/forge_module.dart';
import 'package:get_it/get_it.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../interface/backend_service.dart';
import '../supabase/supabase_backend_service.dart';

enum BackendProvider { supabase, firebase }

/// BackendModule — registers the appropriate [BackendService] implementation.
///
/// In main.dart:
/// ```dart
/// await initServiceLocator(modules: [
///   BackendModule(
///     provider: BackendProvider.supabase,
///     supabaseUrl: ForgeEnv.get('SUPABASE_URL'),
///     supabaseAnonKey: ForgeEnv.get('SUPABASE_ANON_KEY'),
///   ),
/// ]);
/// ```
class BackendModule implements ForgeModule {
  final BackendProvider provider;
  final String? supabaseUrl;
  final String? supabaseAnonKey;

  const BackendModule({
    required this.provider,
    this.supabaseUrl,
    this.supabaseAnonKey,
  });

  @override
  Future<void> register(GetIt sl) async {
    switch (provider) {
      case BackendProvider.supabase:
        await _initSupabase(sl);
      case BackendProvider.firebase:
        await _initFirebase(sl);
    }
  }

  Future<void> _initSupabase(GetIt sl) async {
    assert(supabaseUrl != null && supabaseAnonKey != null,
        'supabaseUrl and supabaseAnonKey are required for Supabase backend');

    await Supabase.initialize(
      url: supabaseUrl!,
      anonKey: supabaseAnonKey!,
    );

    sl.registerSingleton<BackendService>(
      SupabaseBackendService(client: Supabase.instance.client),
    );
  }

  Future<void> _initFirebase(GetIt sl) async {
    // Firebase initialization is handled in firebase_options.dart
    // generated by `flutterfire configure`.
    // Import and call: await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    throw UnimplementedError(
      'Firebase backend: run `flutterfire configure` then implement FirebaseBackendService. '
      'See packages/forge_backend/lib/src/firebase/ for the template.',
    );
  }
}
